server:
  port: 7070

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:db/schema.sql

mybatis-crypto:
  fail-fast: true
  default-encryptor: io.github.whitedg.mybatis.crypto.AES256Encryptor
  default-key: DEFAULT-KEY
  mapped-key-prefixes: et, encrypted

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
